name: it
on:
  schedule:
    - cron: "0 */24 * * *"
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '18'
      - run: npm install
      - run: npm run grab -- --channels=./channels/it.channels.xml --gzip --output=./guide/epg-it.xml --days=7
      - uses: [_load]
